"""Tier-3 mutation corpus — the merge-blocking ≥95% bar (ROADMAP.md §5.3, §1).

Per §5.3: take a known-good fixture (an element tier 1/2 resolved correctly),
apply a battery of realistic DOM mutations generated by `hypothesis` — class
renames, attribute shuffles, sibling reordering, added wrapper elements, text
changes, and combinations of them at increasing severity — then assert tier 3
still re-resolves the *correct* element. The tracked output is a **success rate
against the corpus**, and the v1 bar is **≥95%** (§5.3, decided). That number,
not a one-time claim, is what "reliable" means here; it gates a Phase-3 "done"
call and any change touching tier 3 (CLAUDE.md).

Mutations are applied site-wide (every product's class is renamed, not just the
target's), which is the honest hard case: the volatile signals stop
distinguishing the target from its peers, so healing must lean on what survives
(text, tag, structure). Correctness is checked by lxml element *identity* — the
same element object is tracked through the mutations — so nothing in the scorer
can cheat by reading a test-only marker.

Severity (§5.3): `change_text` spans light touches (a badge suffix, a single-word
swap) through to a full reword that replaces every word — the realistic range a
redesign produces. When a full reword lands on the target *and* the same plan
also churns its class, other attributes, and id, no distinguishing anchor
survives and the target becomes indistinguishable from its identically-structured
peers; tier 3 is expected to (correctly) fail a small minority of those, well
inside the ≥95% budget. That total-anchor-loss case is also, by design, the
uncertain-match path (a sub-threshold best candidate flagged for review rather
than used) exercised directly in features/self_healing.feature. Empirically this
corpus sits at ~99.8% (min ~99.3% across independent batches), so the bar is a
live regression gate with margin, not a vacuous 100%.

Run: pytest -m mutation
"""

from __future__ import annotations

import random
from dataclasses import dataclass

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st
from lxml import html as lxml_html
from lxml.html import HtmlElement
from parsel import Selector

from spoor.core.healing import fingerprint, heal

# The known-good page: a product listing tier 1/2 would resolve cleanly. Every
# product carries the same structural shape and class vocabulary, so once a
# mutation churns those uniformly, only per-item text/attributes/position tell
# them apart — exactly the pressure tier 3 must withstand.
_PRODUCTS = [
    ("p-11", "SKU-11", "Alpha Widget"),
    ("p-22", "SKU-22", "Beta Gadget"),
    ("p-33", "SKU-33", "Deluxe Titanium Spork"),
    ("p-44", "SKU-44", "Gamma Contraption"),
    ("p-55", "SKU-55", "Economy Paperclip"),
    ("p-66", "SKU-66", "Vintage Hand Fan"),
]
_TARGET_ID = "p-33"  # located before mutation; may be renamed by the mutation

_CARDS = "\n".join(
    f'<li class="product-card" data-idx="{i}">'
    f'<a id="{pid}" class="product-link featured" data-sku="{sku}" href="/p/{pid}">'
    f"{name}</a>"
    f'<span class="price">$9.99</span></li>'
    for i, (pid, sku, name) in enumerate(_PRODUCTS)
)
_PAGE = f"""
<html><body>
  <header><h1 class="site-title">Shop</h1></header>
  <nav><a href="/">Home</a><a href="/cart">Cart</a></nav>
  <main><ul class="product-grid">{_CARDS}</ul></main>
  <footer><small class="copyright">(c) shop</small></footer>
</body></html>
"""

_MUTATIONS = (
    "rename_classes",
    "drop_classes",
    "rename_attrs",
    "reorder_siblings",
    "add_wrapper",
    "change_text",
    "rename_ids",
)


@dataclass(frozen=True)
class MutationPlan:
    """A generated markup change: which mutation ops to apply, and a seed for the
    per-op random choices so the whole thing is reproducible from the plan."""

    ops: tuple[str, ...]
    seed: int


def _plans() -> st.SearchStrategy[MutationPlan]:
    return st.builds(
        MutationPlan,
        ops=st.lists(
            st.sampled_from(_MUTATIONS), min_size=1, max_size=5, unique=True
        ).map(tuple),
        seed=st.integers(min_value=0, max_value=2**31 - 1),
    )


def _elements(tree: HtmlElement) -> list[HtmlElement]:
    return [el for el in tree.iter() if isinstance(el.tag, str)]


def _rename_classes(tree: HtmlElement, rng: random.Random) -> None:
    suffix = rng.choice(("-v2", "-x", "__new", "-2024"))
    for el in _elements(tree):
        cls = el.get("class")
        if cls:
            el.set("class", " ".join(f"{tok}{suffix}" for tok in cls.split()))


def _drop_classes(tree: HtmlElement, rng: random.Random) -> None:
    for el in _elements(tree):
        if el.get("class") is not None:
            del el.attrib["class"]


def _rename_attrs(tree: HtmlElement, rng: random.Random) -> None:
    # Rename data-* keys and churn their values — the volatile attribute signal.
    for el in _elements(tree):
        for key in [k for k in el.attrib if k.startswith("data-")]:
            value = el.attrib.pop(key)
            el.set(key.replace("data-", "data-x-"), f"{value}-{rng.randint(0, 9)}")


def _reorder_siblings(tree: HtmlElement, rng: random.Random) -> None:
    for parent in _elements(tree):
        children = list(parent)
        if len(children) > 1:
            shuffled = children[:]
            rng.shuffle(shuffled)
            for child in children:
                parent.remove(child)
            parent.extend(shuffled)


def _add_wrapper(tree: HtmlElement, rng: random.Random) -> None:
    # Wrap a random subset of elements (the target may be among them) in a new
    # container, deepening the ancestor chain.
    for el in _elements(tree):
        parent = el.getparent()
        if parent is None or rng.random() > 0.4:
            continue
        wrapper = lxml_html.Element("div")
        wrapper.set("class", "wrap")
        parent.replace(el, wrapper)
        wrapper.append(el)


def _change_text(tree: HtmlElement, rng: random.Random) -> None:
    # Text churn at varying severity, per element: usually a light touch (badge
    # suffix or single-word swap), but sometimes a heavy reword that replaces
    # most of the words — the case that genuinely stresses healing when it lands
    # together with class/attr/id loss. Never a *full* wipe of the sole anchor on
    # an otherwise-anchorless element (see the module's scope note).
    badges = ("New", "Pro", "Plus", "Sale", "2024")
    fillers = ("Item", "Product", "Model", "Edition", "Series")
    for el in _elements(tree):
        if not (el.text and el.text.strip() and not len(el)):
            continue
        words = el.text.split()
        roll = rng.random()
        if len(words) >= 2 and roll < 0.15:
            # Full reword: every word replaced. The hardest text case — when it
            # lands on the target together with class/attr/id loss there may be no
            # anchor left, and tier 3 is expected to (correctly) fail some of those.
            el.text = " ".join(rng.choice(fillers) for _ in words)
        elif len(words) >= 3 and roll < 0.4:
            # Heavy reword: keep one original word, replace the rest.
            keep = rng.randrange(len(words))
            el.text = " ".join(
                w if i == keep else rng.choice(fillers) for i, w in enumerate(words)
            )
        elif len(words) > 1 and roll < 0.7:
            words[rng.randrange(len(words))] = rng.choice(badges)
            el.text = " ".join(words)
        else:
            el.text = f"{el.text.strip()} {rng.choice(badges)}"


def _rename_ids(tree: HtmlElement, rng: random.Random) -> None:
    for el in _elements(tree):
        if el.get("id") is not None:
            el.set("id", f"{el.get('id')}-r{rng.randint(0, 9)}")


_APPLY = {
    "rename_classes": _rename_classes,
    "drop_classes": _drop_classes,
    "rename_attrs": _rename_attrs,
    "reorder_siblings": _reorder_siblings,
    "add_wrapper": _add_wrapper,
    "change_text": _change_text,
    "rename_ids": _rename_ids,
}


def _heals_correctly(plan: MutationPlan) -> bool:
    """Capture the target's fingerprint on the clean page, apply the plan to a
    fresh copy, and return whether tier 3 re-resolves the same element object."""
    clean = lxml_html.fromstring(_PAGE)
    stored = fingerprint(Selector(root=clean.get_element_by_id(_TARGET_ID)))

    mutated = lxml_html.fromstring(_PAGE)
    target = mutated.get_element_by_id(_TARGET_ID)  # located before mutation
    rng = random.Random(plan.seed)
    for op in plan.ops:
        _APPLY[op](mutated, rng)

    candidates = [Selector(root=el) for el in _elements(mutated)]
    result = heal(stored, candidates)
    return result is not None and result.element.root is target


# A single example draws one large batch of plans, so the assertion is a true
# corpus success *rate* (not a per-example pass/fail, which would demand 100%).
# derandomize makes the tracked number reproducible for a given code version.
_CORPUS_SIZE = 300
_REQUIRED_RATE = 0.95


@pytest.mark.mutation
@settings(
    max_examples=1,
    deadline=None,
    derandomize=True,
    suppress_health_check=[HealthCheck.data_too_large],
)
@given(batch=st.lists(_plans(), min_size=_CORPUS_SIZE, max_size=_CORPUS_SIZE))
def test_tier3_resolves_the_correct_element_across_the_mutation_corpus(
    batch: list[MutationPlan],
) -> None:
    successes = sum(_heals_correctly(plan) for plan in batch)
    rate = successes / len(batch)
    # Printed so the tracked number is visible in the run output (§5.3).
    print(
        f"\ntier-3 mutation-corpus success rate: "
        f"{rate:.3f} ({successes}/{len(batch)})"
    )
    assert rate >= _REQUIRED_RATE, (
        f"tier-3 corpus success rate {rate:.3f} fell below the "
        f"{_REQUIRED_RATE:.0%} bar (§5.3) — a regression in self-healing accuracy"
    )


@pytest.mark.mutation
@given(plan=_plans())
@settings(max_examples=50, deadline=None)
def test_every_single_mutation_class_still_returns_a_scored_result(
    plan: MutationPlan,
) -> None:
    # Independent of accuracy: heal must always come back with a scored result and
    # ordered runner-ups for a non-empty page, so the choice is always explainable.
    clean = lxml_html.fromstring(_PAGE)
    stored = fingerprint(Selector(root=clean.get_element_by_id(_TARGET_ID)))
    mutated = lxml_html.fromstring(_PAGE)
    rng = random.Random(plan.seed)
    for op in plan.ops:
        _APPLY[op](mutated, rng)
    result = heal(stored, [Selector(root=el) for el in _elements(mutated)])
    assert result is not None
    assert 0.0 <= result.score <= 1.0
    scores = [r.score for r in result.runners_up]
    assert scores == sorted(scores, reverse=True)
