"""Generate replayable pytest regression tests from an exploration graph (§2g).

Sub-slice 2g-i, the pure generator — no browser and no disk in `build_tests`, exactly
the split the wiki renderer took (6a). §2g's premise is that a captured map is already
a golden-master record (state X, action Y, produced signal bundle Z), so exporting it
as a runnable test is the last-mile step. For each mapped `Transition` this emits a
pytest test that drives Playwright to **replay the reset-and-replay path** that reached
the transition's from-state (reconstructed from the recorded edges), **fire the
action**, and **assert the signals the action was recorded to add** still appear — a
real regression test the consuming team runs against the live product, not a check of
the map's own internal consistency.

The generated files are a **shared-output surface**, so §2h redaction is mandatory:
every captured value written into them (console lines, storage keys, request URLs,
action names, the target URL) passes through `spoor.security.redaction.redact` first.
That has a consequence the wiki did not face — a generated test *asserts* recorded
values against the live page's *raw* runtime values, so both sides must be redacted
like-for-like or a redacted expectation could never match. The suite therefore redacts
the live values it observes with the same primitive before comparing (`redact_all` in
the emitted `_spoor_testkit`), so an assertion checks that behaviour *as Spoor records
and shares it* is unchanged, and no raw secret is ever baked into a test. Running the
suite consequently needs `ht-spoor` (for `redact`) and `playwright` installed — a
deliberate, recorded dependency, taken because the §2h-safe alternative (emitting the
raw secret so the assertion matches) is a non-negotiable violation.

Two honest limitations are recorded here. (1) Only the **additive string signals**
(console, storage, network) are asserted; the accessibility-node delta and the
screenshot hash are not, because reproducing them in the generated runtime needs
Spoor's CDP a11y read and visual hasher — a larger surface deferred to a follow-on,
the same staged deferral the wiki took for screenshot *images*. (2) An action whose
accessible **name itself contains a secret** is redacted like any shared value, so the
emitted role locator would not match the live element — accepted as rare (accessible
names are UI labels, essentially never secrets) and preferred over the §2h violation of
writing the raw name. Nothing here is site-specific (§0): one emitter for every target.
"""

from __future__ import annotations

from collections import deque

from spoor.exploration.discovery import ActionableElement
from spoor.exploration.graph import ExplorationGraph, Transition
from spoor.security.redaction import redact

# The stable filenames of the two fixed support modules the suite always carries.
_TESTKIT = "_spoor_testkit.py"
_CONFTEST = "conftest.py"
_SHORT_ID = 12  # state ids are 64-char hashes; a short prefix labels a test readably

_TESTKIT_SOURCE = '''\
"""Shared helpers for the generated Spoor regression suite (ROADMAP.md §2g).

Generated by Spoor from a captured exploration map; do not edit by hand. Running the
suite needs `ht-spoor` and `playwright` installed: the tests drive a real browser and
redact the live values they observe with Spoor's own redaction primitive before
comparing, so an assertion checks that behaviour as Spoor records and shares it is
unchanged and no raw secret is baked into a test.
"""

from __future__ import annotations

from spoor.security.redaction import redact

TARGET = {target!r}


def redact_all(items):
    """Redact each observed value, so it compares like-for-like with a recorded one."""
    return [redact(item) for item in items]


def storage_keys(page):
    """The live page's localStorage + sessionStorage keys."""
    return page.evaluate(
        "() => [...Object.keys(localStorage), ...Object.keys(sessionStorage)]"
    )


def fire(page, role, name):
    """Click an element by ARIA role and optional accessible name, first match."""
    if name:
        locator = page.get_by_role(role, name=name, exact=True)
    else:
        locator = page.get_by_role(role)
    locator.first.click()
    page.wait_for_load_state()


def reach(page, path):
    """Reset to the target and replay the recorded path of (role, name) actions."""
    page.goto(TARGET)
    page.wait_for_load_state()
    for role, name in path:
        fire(page, role, name)
'''

_CONFTEST_SOURCE = '''\
"""Pytest fixtures for the generated Spoor regression suite (ROADMAP.md §2g).

Generated by Spoor; do not edit by hand.
"""

from __future__ import annotations

import pytest
from playwright.sync_api import sync_playwright


@pytest.fixture
def page():
    """A fresh Chromium page recording the console messages and requests it sees."""
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch()
        pg = browser.new_context().new_page()
        pg.spoor_console = []
        pg.spoor_network = []
        pg.on("console", lambda message: pg.spoor_console.append(message.text))
        pg.on("request", lambda request: pg.spoor_network.append(request.url))
        try:
            yield pg
        finally:
            browser.close()
'''


def build_tests(graph: ExplorationGraph, *, target: str) -> dict[str, str]:
    """Render an exploration graph into a pytest suite: filename -> source (§2g).

    Emits nothing for a graph with no transitions (there is nothing to replay). For a
    non-empty graph, returns the two fixed support modules plus one `test_transition_N`
    file per mapped transition, in the graph's transition order. Pure — no disk, no
    browser; `render_suite` (a thin writer, sub-slice 2g-ii) puts these on disk.
    """
    transitions = graph.transitions
    if not transitions:
        return {}
    paths = _paths_from_root(graph)
    files = {
        _TESTKIT: _TESTKIT_SOURCE.format(target=redact(target)),
        _CONFTEST: _CONFTEST_SOURCE,
    }
    for index, transition in enumerate(transitions):
        path = paths.get(transition.from_state, [])
        files[f"test_transition_{index}.py"] = _render_test(index, transition, path)
    return files


def _paths_from_root(
    graph: ExplorationGraph,
) -> dict[str, list[ActionableElement]]:
    """The reset-and-replay action path from the root to every reachable state (§2g).

    The root is the first state added (the state the explorer started from). A
    breadth-first walk over the recorded transitions gives the shortest edge path to
    each state; the actions along it are what a test replays to reach that state. A
    state not reachable from the root (should not arise from an explorer run) simply
    has no entry, and its tests start from the target with an empty path.
    """
    states = graph.states
    if not states:
        return {}
    root = states[0]
    predecessor: dict[str, tuple[str, ActionableElement] | None] = {root: None}
    adjacency: dict[str, list[tuple[str, ActionableElement]]] = {}
    for transition in graph.transitions:
        adjacency.setdefault(transition.from_state, []).append(
            (transition.to_state, transition.action)
        )
    queue: deque[str] = deque([root])
    while queue:
        state = queue.popleft()
        for to_state, action in adjacency.get(state, []):
            if to_state not in predecessor:
                predecessor[to_state] = (state, action)
                queue.append(to_state)
    paths: dict[str, list[ActionableElement]] = {}
    for state in predecessor:
        sequence: list[ActionableElement] = []
        cursor: str | None = state
        while cursor is not None and predecessor[cursor] is not None:
            previous, action = predecessor[cursor]  # type: ignore[misc]
            sequence.append(action)
            cursor = previous
        paths[state] = list(reversed(sequence))
    return paths


def _locator_args(action: ActionableElement) -> str:
    """The `fire(...)`/path arguments for an action: role and redacted name."""
    return f"{action.role!r}, {redact(action.name)!r}"


def _render_test(
    index: int, transition: Transition, path: list[ActionableElement]
) -> str:
    """Render one transition's regression test source (§2g)."""
    action = transition.action
    label = redact(action.name) or "(unnamed)"
    heading = (
        f"{transition.from_state[:_SHORT_ID]} --{label}--> "
        f"{transition.to_state[:_SHORT_ID]}"
    )
    path_lines = "".join(f"    ({_locator_args(step)}),\n" for step in path)
    body = _assertion_body(transition)
    return (
        "from __future__ import annotations\n\n"
        "from _spoor_testkit import fire, reach, redact_all, storage_keys\n\n"
        f"_PATH = [\n{path_lines}]\n\n\n"
        f"def test_transition_{index}(page):\n"
        f'    """{heading} (replay, fire, assert)."""\n'
        "    reach(page, _PATH)\n"
        f"    fire(page, {_locator_args(action)})\n"
        f"{body}"
    )


def _assertion_body(transition: Transition) -> str:
    """The capture-and-assert lines for a transition's recorded additive signals (§2g).

    Only the additive string signals are asserted (see the module note on the deferred
    a11y/screenshot deltas). A transition with no recorded change gets a smoke test: it
    still replayed and fired the action above, and asserts nothing it never recorded.
    """
    signals = transition.signals
    lines: list[str] = []
    if signals is not None and signals.console_added:
        lines.append("    console = redact_all(page.spoor_console)")
        for message in signals.console_added:
            lines.append(f"    assert {redact(message)!r} in console")
    if signals is not None and signals.storage_added:
        lines.append("    storage = redact_all(storage_keys(page))")
        for key in signals.storage_added:
            lines.append(f"    assert {redact(key)!r} in storage")
    if signals is not None and signals.network_added:
        lines.append("    network = redact_all(page.spoor_network)")
        for url in signals.network_added:
            lines.append(
                f"    assert any({redact(url)!r} in request for request in network)"
            )
    if not lines:
        lines.append("    # no signal changes were recorded for this transition")
    return "\n".join(lines) + "\n"
